set_property PACKAGE_PIN W5 [get_ports clk_100MHz]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk_100MHz]
	
set_property PACKAGE_PIN U16 [get_ports {sequence_leds[1]}]					
    set_property IOSTANDARD LVCMOS33 [get_ports {sequence_leds[1]}]
set_property PACKAGE_PIN E19 [get_ports {sequence_leds[2]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {sequence_leds[2]}]
set_property PACKAGE_PIN U19 [get_ports {sequence_leds[3]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {sequence_leds[3]}]
set_property PACKAGE_PIN V19 [get_ports {sequence_leds[4]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {sequence_leds[4]}]
set_property PACKAGE_PIN W18 [get_ports {sequence_leds[5]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {sequence_leds[5]}]
set_property PACKAGE_PIN U15 [get_ports {sequence_leds[6]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {sequence_leds[6]}]
set_property PACKAGE_PIN U14 [get_ports {password_leds[1]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {password_leds[1]}]
set_property PACKAGE_PIN V14 [get_ports {password_leds[2]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {password_leds[2]}]
set_property PACKAGE_PIN V13 [get_ports {password_leds[3]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {password_leds[3]}]
set_property PACKAGE_PIN V3 [get_ports {password_leds[4]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {password_leds[4]}]
set_property PACKAGE_PIN W3 [get_ports {password_leds[5]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {password_leds[5]}]
set_property PACKAGE_PIN U3 [get_ports {password_leds[6]}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {password_leds[6]}]
set_property PACKAGE_PIN P3 [get_ports {sync_led}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {sync_led}]
set_property PACKAGE_PIN N3 [get_ports {lock_led}]                    
    set_property IOSTANDARD LVCMOS33 [get_ports {lock_led}]


##Sch name = JC4
set_property PACKAGE_PIN P18 [get_ports {btn}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {btn}]

##Buttons
set_property PACKAGE_PIN U18 [get_ports {res}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {res}]
	set_property IOSTANDARD LVCMOS33 [get_ports {pass}]
set_property PACKAGE_PIN T17 [get_ports {pass}]	
